site_name: 'Holiday Tracker Plugin'
docs_dir: docs
repo_url: https://github.com/Infosys/holiday-tracker-plugin
plugins:
  - techdocs-core

nav:
  - Overview:
      - What is Holiday Tracker Plugin?: 'holidaytracker.md'
      - How to install the plugin?: 'holidayplugin.md'
